FROM golang:1.24 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN apt-get update && apt-get install -y gcc libc6-dev libsqlite3-dev
RUN CGO_ENABLED=1 GOOS=linux go build -o consumer ./cmd/consumer

FROM alpine:3.21
RUN apk add --no-cache sqlite-libs
WORKDIR /app
COPY --from=builder /app/consumer .
CMD [ "./consumer" ]