// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: proto/argus.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArgusService_SendSnapshot_FullMethodName = "/argus.ArgusService/SendSnapshot"
)

// ArgusServiceClient is the client API for ArgusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArgusServiceClient interface {
	SendSnapshot(ctx context.Context, in *Snapshot, opts ...grpc.CallOption) (*Ack, error)
}

type argusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArgusServiceClient(cc grpc.ClientConnInterface) ArgusServiceClient {
	return &argusServiceClient{cc}
}

func (c *argusServiceClient) SendSnapshot(ctx context.Context, in *Snapshot, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, ArgusService_SendSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArgusServiceServer is the server API for ArgusService service.
// All implementations must embed UnimplementedArgusServiceServer
// for forward compatibility.
type ArgusServiceServer interface {
	SendSnapshot(context.Context, *Snapshot) (*Ack, error)
	mustEmbedUnimplementedArgusServiceServer()
}

// UnimplementedArgusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArgusServiceServer struct{}

func (UnimplementedArgusServiceServer) SendSnapshot(context.Context, *Snapshot) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendSnapshot not implemented")
}
func (UnimplementedArgusServiceServer) mustEmbedUnimplementedArgusServiceServer() {}
func (UnimplementedArgusServiceServer) testEmbeddedByValue()                      {}

// UnsafeArgusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArgusServiceServer will
// result in compilation errors.
type UnsafeArgusServiceServer interface {
	mustEmbedUnimplementedArgusServiceServer()
}

func RegisterArgusServiceServer(s grpc.ServiceRegistrar, srv ArgusServiceServer) {
	// If the following call pancis, it indicates UnimplementedArgusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArgusService_ServiceDesc, srv)
}

func _ArgusService_SendSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Snapshot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArgusServiceServer).SendSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArgusService_SendSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArgusServiceServer).SendSnapshot(ctx, req.(*Snapshot))
	}
	return interceptor(ctx, in, info, handler)
}

// ArgusService_ServiceDesc is the grpc.ServiceDesc for ArgusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArgusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.ArgusService",
	HandlerType: (*ArgusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSnapshot",
			Handler:    _ArgusService_SendSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/argus.proto",
}
